# Generated by Django 2.2.6 on 2020-06-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200602_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
