# Generated by Django 2.2.6 on 2020-06-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200604_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='username',
            new_name='user',
        ),
    ]
